services:
  sainik-library:
    build: .
    container_name: sainik-library
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      DB_FILE: /data/sainik.db
    volumes:
      - ./data:/data
    restart: unless-stopped
